package dpfm_api_input_reader

type EC_MC struct {
}

type SDC struct {
	ConnectionKey       string             `json:"connection_key"`
	Result              bool               `json:"result"`
	RedisKey            string             `json:"redis_key"`
	Filepath            string             `json:"filepath"`
	APIStatusCode       int                `json:"api_status_code"`
	RuntimeSessionID    string             `json:"runtime_session_id"`
	BusinessPartnerID   *int               `json:"business_partner"`
	ServiceLabel        string             `json:"service_label"`
	AccountingDocument  AccountingDocument `json:"AccountingDocument"`
	APISchema           string             `json:"api_schema"`
	Accepter            []string           `json:"accepter"`
	OrderID             *int               `json:"order_id"`
	Deleted             bool               `json:"deleted"`
	SQLUpdateResult     *bool              `json:"sql_update_result"`
	SQLUpdateError      string             `json:"sql_update_error"`
	SubfuncResult       *bool              `json:"subfunc_result"`
	SubfuncError        string             `json:"subfunc_error"`
	ExconfResult        *bool              `json:"exconf_result"`
	ExconfError         string             `json:"exconf_error"`
	APIProcessingResult *bool              `json:"api_processing_result"`
	APIProcessingError  string             `json:"api_processing_error"`
}

type AccountingDocument struct {
	AccountingDocument             string   `json:"AccountingDocument"`
	AccountingDocumentItem         string   `json:"AccountingDocumentItem"`
	FiscalYear                     string   `json:"FiscalYear"`
	ChartOfAccounts                string   `json:"ChartOfAccounts"`
	AccountingDocumentItemType     string   `json:"AccountingDocumentItemType"`
	ClearingDate                   *string  `json:"ClearingDate"`
	ClearingCreationDate           *string  `json:"ClearingCreationDate"`
	ClearingAccountingDocument     string   `json:"ClearingAccountingDocument"`
	IsCleared                      *bool    `json:"IsCleared"`
	PostingKey                     string   `json:"PostingKey"`
	DebitCreditCode                string   `json:"DebitCreditCode"`
	BusinessArea                   string   `json:"BusinessArea"`
	TaxCode                        string   `json:"TaxCode"`
	TaxType                        string   `json:"TaxType"`
	DocumentItemText               string   `json:"DocumentItemText"`
	OrderID                        *int     `json:"OrderID"`
	OrderItem                      *int     `json:"OrderItem"`
	OrderType                      string   `json:"OrderType"`
	ContractType                   string   `json:"ContractType"`
	InvoiceDocument                *int     `json:"InvoiceDocument"`
	InvoiceDocumentItem            *int     `json:"InvoiceDocumentItem"`
	ScheduleLine                   *int     `json:"ScheduleLine"`
	IsOpenItemManaged              *bool    `json:"IsOpenItemManaged"`
	IsAutomaticallyCreated         *bool    `json:"IsAutomaticallyCreated"`
	GLAccount                      string   `json:"GLAccount"`
	GLAccountName                  string   `json:"GLAccountName"`
	Customer                       *int     `json:"Customer"`
	Supplier                       *int     `json:"Supplier"`
	IsBalanceSheetAccount          *bool    `json:"IsBalanceSheetAccount"`
	ProfitLossAccountType          string   `json:"ProfitLossAccountType"`
	DueCalculationBaseDate         *string  `json:"DueCalculationBaseDate"`
	PaymentTerms                   string   `json:"PaymentTerms"`
	NetPaymentDays                 string   `json:"NetPaymentDays"`
	PaymentMethod                  string   `json:"PaymentMethod"`
	PaymentBlockStatus             string   `json:"PaymentBlockStatus"`
	HouseBank                      string   `json:"HouseBank"`
	FinInstIdentification          string   `json:"FinInstIdentification"`
	InvoiceReference               string   `json:"InvoiceReference"`
	InvoiceReferenceFiscalYear     string   `json:"InvoiceReferenceFiscalYear"`
	InvoiceItemReference           string   `json:"InvoiceItemReference"`
	SupplyingCountry               string   `json:"SupplyingCountry"`
	Material                       string   `json:"Material"`
	Plant                          string   `json:"Plant"`
	IsCompletelyDelivered          *bool    `json:"IsCompletelyDelivered"`
	InventoryValuationType         string   `json:"InventoryValuationType"`
	ClearingIsReversed             *bool    `json:"ClearingIsReversed"`
	CreditControlArea              string   `json:"CreditControlArea"`
	ClearingItem                   string   `json:"ClearingItem"`
	ClearingDocFiscalYear          string   `json:"ClearingDocFiscalYear"`
	HouseBankAccount               string   `json:"HouseBankAccount"`
	ReferenceDocumentType          string   `json:"ReferenceDocumentType"`
	OriginalReferenceDocument      string   `json:"OriginalReferenceDocument"`
	AccountingDocumentItemRef      string   `json:"AccountingDocumentItemRef"`
	FiscalPeriod                   string   `json:"FiscalPeriod"`
	PostingDate                    *string  `json:"PostingDate"`
	DocumentDate                   *string  `json:"DocumentDate"`
	AccountingDocumentType         string   `json:"AccountingDocumentType"`
	NetDueDate                     *string  `json:"NetDueDate"`
	TransactionCurrency            string   `json:"TransactionCurrency"`
	AmountInTransactionCurrency    string   `json:"AmountInTransactionCurrency"`
	OriginalTaxBaseAmount          *float32 `json:"OriginalTaxBaseAmount"`
	TaxAmount                      *float32 `json:"TaxAmount"`
	TaxBaseAmountInTransCrcy       string   `json:"TaxBaseAmountInTransCrcy"`
	BaseUnit                       string   `json:"BaseUnit"`
	Quantity                       string   `json:"Quantity"`
	GoodsMovementEntryUnit         string   `json:"GoodsMovementEntryUnit"`
	QuantityInEntryUnit            string   `json:"QuantityInEntryUnit"`
	AccountingDocumentCreationDate *string  `json:"AccountingDocumentCreationDate"`
	CreationTime                   *string  `json:"CreationTime"`
	LastChangeDate                 *string  `json:"LastChangeDate"`
	ExchangeRateDate               *string  `json:"ExchangeRateDate"`
	IntercompanyTransaction        string   `json:"IntercompanyTransaction"`
	DocumentReferenceID            string   `json:"DocumentReferenceID"`
	ReverseDocument                string   `json:"ReverseDocument"`
	ReverseDocumentFiscalYear      string   `json:"ReverseDocumentFiscalYear"`
	AccountingDocumentHeaderText   string   `json:"AccountingDocumentHeaderText"`
	ExchangeRate                   *float32 `json:"ExchangeRate"`
	TaxIsCalculatedAutomatically   string   `json:"TaxIsCalculatedAutomatically"`
	Reference1InDocumentHeader     string   `json:"Reference1InDocumentHeader"`
	Reference2InDocumentHeader     string   `json:"Reference2InDocumentHeader"`
	IsReversed                     *bool    `json:"IsReversed"`
}
